name: Restrict PRs to Main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict:
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR is from develop
        run: |
          echo "Source branch: ${{ github.head_ref }}"
          if [ "${{ github.head_ref }}" != "develop" ]; then
            echo "❌ Pull requests to 'main' are only allowed from 'develop' branch."
            exit 1
          fi
